name: Deploy ADF to Target Factory

on:
  push:
    branches:
      - adf_publish

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout publish branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ARM template to Target ADF
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
          template: Roadtofang/ARMTemplateForFactory.json
          parameters: >
            Roadtofang/ARMTemplateParametersForFactory.json
            factoryName=${{ secrets.ADF_TARGET_NAME }}
          deploymentMode: Incremental
